# **Álgebra Linear na Ciência de Dados**

**Criando vetores e matrizes no Python**

Para criar vetores e matrizes no Python basta criar listas e depois convertê-las para Numpy Arrays:

In [1]:
import numpy as np

Vetores:

In [2]:
#Criando lista
x=[1,4,2,9]
print(type(x))

#Convertendo
x=np.array(x)
print(type(x)) #já temos um vetor criado

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
#Printando Vetor
print(x)

[1 4 2 9]


In [4]:
#Verificando o "shape"

print(x.shape) #O vetor "x" tem tamanho 4

(4,)


In [5]:
print(type(np.r_[1,2,3]))

<class 'numpy.ndarray'>


Matrizes:

In [6]:
#Para criar matrizes é necessário criar listas dentro da lista principal,
#sendo que cada lista interna representa uma linha da matriz.

#Criando lista
A=[[1,4,2],[6,2,8],[3,7,7],[3,4,2]]
print(type(A))

#Convertendo
A=np.array(A)
print(type(A)) #já temos um vetor criado

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
print(A)

[[1 4 2]
 [6 2 8]
 [3 7 7]
 [3 4 2]]


In [8]:
#Verificando o "shape"
print(A.shape) #"A" tem 4 linhas e 3 colunas

(4, 3)


Selecionando colunas e linhas específicas da matriz A:

In [9]:
print(A[0,:])

[1 4 2]


In [10]:
print(A[:,2])

[2 8 7 2]


In [11]:
print(A[:2,1:])

[[4 2]
 [2 8]]


Criando alguns vetores e matrizes específicos:

In [12]:
x = np.ones(3)  #vetor somente composto de "uns"
y = np.zeros(3) #vetor somente composto de "zeros"

print(x)
print(y)

[1. 1. 1.]
[0. 0. 0.]


In [13]:
A = np.ones((2,3))  #matriz (2x3) somente composto de "uns"
B = np.zeros((2,3)) #matriz (2x3) somente composto de "zeros"

print(A)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


**Operações com matrizes e vetores**

Soma e subtração:

In [14]:
x=np.array([1,4,2,9])
y=np.array([2,1,3,0])

print(x+y)
print(x-y)

[3 5 5 9]
[-1  3 -1  9]



Produto por um escalar $\alpha$:

In [15]:
x=np.array([1,4,2,9])
alpha=2

print(x)
print(alpha*x)

[1 4 2 9]
[ 2  8  4 18]


Transposição:

In [16]:
A=np.array([[1,4,2],[6,2,8]])
print(A)

[[1 4 2]
 [6 2 8]]


In [17]:
print(A.T) #transposta: colocar ".T" no fim

[[1 6]
 [4 2]
 [2 8]]


Produto de matrizes:

In [19]:
A=np.array([[1,4,2],[6,2,8]])
B=np.array([[3,7,7],[3,4,2]])

In [20]:
#usando a transposta de B (B.T)
C=np.matmul(A,B.T)
print(C)

[[45 23]
 [88 42]]


In [21]:
#Outra maneira
C=A.dot(B.T)
print(C)

[[45 23]
 [88 42]]


Produto elemento a elemento (element wise product)

In [22]:
x=np.array([1,4,2,9])
y=np.array([2,1,3,0])

print(x*y)

[2 4 6 0]
